#!/bin/bash

if [ -z "$1" ]; then
  echo "Error: Missing required parameter ig"
  echo "Usage: $0 [core|eps|medication|lab|hdr]"
  exit 1
fi
ig="$1"

tx --use-env

if [[ -f ~/.env_ig ]]; then
	source ~/.env_ig
fi

if [[ $USE_NTS == "y" ]]; then
	echo "Starting proxy for the Nationale Terminologieserver"
	export NTS_USER
	export NTS_PASS
	mitmdump -s /tools/NTS-proxy.py > /dev/null &
	proxy_process=$!
	sleep 2s
	curl_line="--proxy http://localhost:8080 http://terminologieserver.nl/fhir/metadata"
else
	curl_line="https://tx.fhir.org"
fi

echo Checking internet connection...
curl -sSf $curl_line > /dev/null
if [ $? -eq 0 ]; then
	if [[ $USE_NTS == "y" ]]; then
		echo "Using the Nationale Terminologieserver"
		txoption="-proxy localhost:8080 -tx http://terminologieserver.nl/fhir"
	else
		echo "Using the default terminology server (tx.fhir.org)"
		txoption=""
	fi
else
	echo "Offline"
	txoption="-tx n/a"
fi

# Make sure the global package cache is locally available
mkdir -p ~/.fhir/packages
for pkg in /var/lib/.fhir/packages/*; do
    if [ -d "$pkg" ]; then # Only process directories
        pkg_name=$(basename "$pkg")
        dest_pkg="$HOME/.fhir/packages/$pkg_name"

        if [ ! -d "$dest_pkg" ]; then
            cp -r "$pkg" "$dest_pkg" # Copying, because symlinking seems to confuse the Validator
        fi
    fi
done

echo "Scanning input/resources for FHIR resource"
python3 /tools/createIG.py --ig $ig
echo

publisher_jar=publisher.jar
input_cache_path=/tools/
export JAVA_TOOL_OPTIONS="$JAVA_TOOL_OPTIONS -Dfile.encoding=UTF-8"

publisher=$input_cache_path/$publisher_jar
if test -f "$publisher"; then
	java -jar $publisher -ig . $txoption $*

else
	publisher=../$publisher_jar
	if test -f "$publisher"; then
		java -jar $publisher -ig . $txoption $*
	else
		echo IG Publisher NOT FOUND in input-cache or parent folder.  Please run _updatePublisher.  Aborting...
	fi
fi

if [[ $USE_NTS == "y" ]]; then
	kill $proxy_process
fi