#!/bin/bash

if [[ -f ~/.env_ig ]]; then
	source ~/.env_ig
fi

if [[ -z "$USE_NTS" ]]; then
	echo -n "Do you have an account for the Nationale Terminologieserver that you want to use? (y/n) "
	read use_nts
	if [[ $use_nts == "y" || $use_nts == "Y" ]]; then
		USE_NTS="y"
		echo "USE_NTS=y" > ~/.env_ig
	else
		USE_NTS="n"
		echo "USE_NTS=n" > ~/.env_ig
	fi

	if [[ $use_nts = "y" ]]; then
		echo -n "What's your username? "
		read NTS_USER
		echo -n "What's your password? "
		read -s NTS_PASS
		echo
		echo "NTS_USER=$NTS_USER" >> ~/.env_ig
		echo "NTS_PASS=$NTS_PASS" >> ~/.env_ig
	fi
fi

if [[ $USE_NTS == "y" ]]; then
	echo "Starting proxy for the Nationale Terminologieserver"
	export NTS_USER
	export NTS_PASS
	mitmdump -s /tools/NTS-proxy.py > /dev/null &
	proxy_process=$!
	sleep 2s
	curl_line="--proxy http://localhost:8080 http://terminologieserver.nl/fhir/metadata"
else
	curl_line="https://tx.fhir.org"
fi

echo Checking internet connection...
curl -sSf $curl_line > /dev/null
if [ $? -eq 0 ]; then
	if [[ $USE_NTS == "y" ]]; then
		echo "Using the Nationale Terminologieserver"
		txoption="-proxy localhost:8080 -tx http://terminologieserver.nl/fhir"
	else
		echo "Using the default terminology server (tx.fhir.org)"
		txoption=""
	fi
else
	echo "Offline"
	txoption="-tx n/a"
fi

echo "Scanning input/resources for FHIR resource"
python3 /tools/createIG.py
echo

publisher_jar=publisher.jar
input_cache_path=/tools/
export JAVA_TOOL_OPTIONS="$JAVA_TOOL_OPTIONS -Dfile.encoding=UTF-8"

publisher=$input_cache_path/$publisher_jar
if test -f "$publisher"; then
	java -jar $publisher -ig . $txoption $*

else
	publisher=../$publisher_jar
	if test -f "$publisher"; then
		java -jar $publisher -ig . $txoption $*
	else
		echo IG Publisher NOT FOUND in input-cache or parent folder.  Please run _updatePublisher.  Aborting...
	fi
fi

if [[ $USE_NTS == "y" ]]; then
	kill $proxy_process
fi